import { extractIocs } from '../ioc/ioc'
import { convertTimestamp, parseTimestamp } from '../timestamp/timestamp'
export const tactics = ['initial-access','execution','persistence','privilege-escalation','defense-evasion','credential-access','discovery','lateral-movement','collection','command-and-control','exfiltration','impact','other'] as const
export type Tactic = typeof tactics[number]
export interface TimelineEntry { id:string; epochMs:number|null; rawTime:string; description:string; tactic:Tactic; host:string; source:string; indicators:string[] }
export interface FlagAnswer { id:string; label:string; value:string; found:boolean; notes:string }; export interface Workspace { entries:TimelineEntry[]; flags:FlagAnswer[] }
const month:Record<string,string>={jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'}
function time(line:string){const w=line.match(/\[(\d{2})\/(\w{3})\/(\d{4}):(\d{2}:\d{2}:\d{2})\s+([+-]\d{4})\]/u);if(w){const ms=Date.parse(`${w[3]}-${month[w[2].toLowerCase()]}-${w[1]}T${w[4]}${w[5]}`);if(!Number.isNaN(ms))return{epochMs:ms,rawTime:w[0]}}const i=line.match(/\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})\b/iu);if(i)try{return{epochMs:parseTimestamp(i[0],'human'),rawTime:i[0]}}catch{/* Tijd blijft ongedateerd. */}const n=line.match(/^\s*(\d{10,19})(?:\s+|$)/u);if(n)try{const r=n[1];return{epochMs:parseTimestamp(r,r.length>=17?'filetime':r.length<=10?'seconds':'milliseconds'),rawTime:r}}catch{/* Tijd blijft ongedateerd. */}const s=line.match(/\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\b/iu);if(s)try{return{epochMs:parseTimestamp(`${new Date().getUTCFullYear()} ${s[0]} UTC`,'human'),rawTime:s[0]}}catch{/* Tijd blijft ongedateerd. */}return{epochMs:null,rawTime:''}}
function iocs(text:string){return[...new Set(extractIocs(text).groups.flatMap((g)=>g.entries.map((e)=>e.value)))]}
export function parseTimelineBlock(input:string,source='parse'){return input.split(/\r?\n/u).filter((x)=>x.trim()).map((line,i)=>{const t=time(line);const host=line.match(/\b(?:host|computer|hostname)\s*[=:]\s*([^\s,;]+)/iu)?.[1]??extractIocs(line).groups.flatMap((g)=>g.entries).find((x)=>x.type==='ipv4'||x.type==='ipv6')?.value??'';return{id:`timeline-${i+1}`,epochMs:t.epochMs,rawTime:t.rawTime,description:line.trim(),tactic:'other' as Tactic,host,source,indicators:iocs(line)}})}
export const parseEvidenceBlock=parseTimelineBlock
export function sortTimeline(es:readonly TimelineEntry[]){return es.map((entry,index)=>({entry,index})).sort((a,b)=>a.entry.epochMs===null?(b.entry.epochMs===null?a.index-b.index:1):b.entry.epochMs===null?-1:a.entry.epochMs-b.entry.epochMs||a.index-b.index).map((x)=>x.entry)}
export function deduplicateTimeline(es:readonly TimelineEntry[]){const seen=new Set<string>();return es.filter((e)=>{const k=`${e.epochMs}\0${e.description}\0${e.host}`;if(seen.has(k))return false;seen.add(k);return true})};export const deduplicateEntries=deduplicateTimeline
export function enrichTimeline(es:readonly TimelineEntry[]){return deduplicateTimeline(sortTimeline(es)).map((e)=>({...e,indicators:iocs(`${e.rawTime} ${e.description}`)}))}
export function timelineMetrics(es:readonly TimelineEntry[]){let p:number|null=null;const r=es.map((e)=>{const deltaMs=e.epochMs===null||p===null?null:e.epochMs-p;if(e.epochMs!==null)p=e.epochMs;return{deltaMs}}) as {deltaMs:number|null}[]&{totalDurationMs:number|null};const d=es.flatMap((e)=>e.epochMs===null?[]:[e.epochMs]);r.totalDurationMs=d.length?d[d.length-1]-d[0]:null;return r};export function deltaMs(es:readonly TimelineEntry[],i:number){return timelineMetrics(es)[i]?.deltaMs??null};export function totalDurationMs(es:readonly TimelineEntry[]){return timelineMetrics(sortTimeline(es)).totalDurationMs}
export function formatZone(ms:number|null,z:'UTC'|'Europe/Amsterdam'){return ms===null?'—':z==='UTC'?convertTimestamp(ms).utc:convertTimestamp(ms).amsterdam};export function formatDuration(ms:number|null){if(ms===null)return'—';const s=Math.floor(ms/1000);return`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m ${s%60}s`}
export function filterTimeline(es:readonly TimelineEntry[],p:Tactic|'all',h:string,l:boolean){return es.filter((e)=>(p==='all'||e.tactic===p)&&(!h||e.host===h)&&(!l||e.indicators.length>0))};export function aggregateIndicators(es:readonly TimelineEntry[]){return[...new Set(es.flatMap((e)=>e.indicators))].sort()};export function saveTimeline(es:readonly TimelineEntry[]){return JSON.stringify(es,null,2)};export function loadTimeline(t:string){const v=JSON.parse(t) as unknown;if(!Array.isArray(v))throw new Error('Invalid timeline JSON');return v as TimelineEntry[]}
export function toCsv(es:readonly TimelineEntry[]){return es.map((e)=>`${formatZone(e.epochMs,'UTC')},${e.description}`).join('\n')};export function toMarkdown(es:readonly TimelineEntry[],label:(x:Tactic)=>string=(x)=>x){return tactics.filter((p)=>es.some((e)=>e.tactic===p)).map((p)=>`## ${label(p)}\n${sortTimeline(es.filter((e)=>e.tactic===p)).map((e)=>`- ${e.epochMs===null?'Undated':`${new Date(e.epochMs).toISOString().slice(11,19)} UTC`} — ${e.description}${e.host?` (${e.host})`:''}`).join('\n')}`).join('\n\n')};export function flagsToCsv(fs:readonly FlagAnswer[]){return fs.map((f)=>`${f.label},${f.value}`).join('\n')};export function flagsToMarkdown(fs:readonly FlagAnswer[]){return fs.map((f)=>`- [${f.found?'x':' '}] ${f.label}: ${f.value}`).join('\n')};export function saveWorkspace(w:Workspace){return JSON.stringify({version:1,...w})}
function validEntry(v:unknown):v is TimelineEntry{if(!v||typeof v!=='object')return false;const e=v as Record<string,unknown>;return typeof e.id==='string'&&(typeof e.epochMs==='number'||e.epochMs===null)&&typeof e.rawTime==='string'&&typeof e.description==='string'&&tactics.includes(e.tactic as Tactic)&&typeof e.host==='string'&&typeof e.source==='string'&&Array.isArray(e.indicators)&&e.indicators.every((x)=>typeof x==='string')} function validFlag(v:unknown):v is FlagAnswer{if(!v||typeof v!=='object')return false;const f=v as Record<string,unknown>;return typeof f.id==='string'&&typeof f.label==='string'&&typeof f.value==='string'&&typeof f.found==='boolean'&&typeof f.notes==='string'} export function loadWorkspace(t:string){const v=JSON.parse(t) as Record<string,unknown>;if(v.version!==1||!Array.isArray(v.entries)||!Array.isArray(v.flags)||!v.entries.every(validEntry)||!v.flags.every(validFlag))throw new Error('Invalid workspace');return{entries:v.entries,flags:v.flags}}
